List<String> CcycleCourses = [
  'Mathematics-1',
  'Mathematics-2',
  'Chemistry',
  'Programming in C and Data Structures',
  'Computer Aided Engineering Drawing',
  'Basic Electronics',
  'Chemistry Lab',
  'Environmental Studies',
  'English'
];
List<String> PcycleCourses = [
  'Mathematics-1',
  'Mathematics-2',
  'Physics',
  'Basic Electrical Engg',
  'Elements of Mechanical Engg',
  'Elements of Civil Engg and Mechanics',
  'Workshop Practice',
  'Physics Lab',
  'Constitution of India and Professional ethics',
  'Kannada'
];

List<String> Ece3Courses = [
  'Mathematics-3',
  'Network Theory',
  'Electronic Devices',
  'Digital System Design',
  'COMPUTER ORGANIZATION AND ARCHITECTURE',
  'POWER ELECTRONICS AND INSTRUMENTATION',
  'ELECTRONIC DEVICES AND INSTRUMENTATION LABORATORY',
  'DIGITAL SYSTEM DESIGN LABORATORY',
];
List<String> Ece4Courses = [
  'Mathematics-4',
  'Analog Circuits',
  'CONTROL SYSTEMS',
  'ENGINEERING STATISTICS and LINEAR ALGEBRA',
  'SIGNALS AND SYSTEMS',
  'MICROCONTROLLER',
  'MICROCONTROLLER LABORATORY',
  'ANALOG CIRCUITS LABORATORY',
  'TECHNOLOGICAL INNOVATION MANAGEMENT AND ENTREPRENEURSHIP'
];
List<String> Ece5Courses = [
  'DIGITAL SIGNAL PROCESSING',
  'PRINCIPLES OF COMMUNICATION SYSTEMS',
  'INFORMATION THEORY and CODING',
  'ELECTROMAGNETIC WAVES',
  'Verilog HDL',
  'DIGITAL SIGNAL PROCESSING LABORATORY',
  'HDL LABORATORY',
  'ENVIRONMENTAL STUDIES',
];

List<String> Ece6Courses = [
  'DIGITAL COMMUNICATION',
  'EMBEDDED SYSTEMS ',
  'MICROWAVE and ANTENNAS',
  'OPERATING SYSTEM',
  'ARITIFICAL NEURAL NETWORKS ',
  'DATA  STRUCTURE  USING C++',
  'DIGITAL SYSTEM DESIGN USING VERILOG',
  'NANOELECTRONICS',
  'PYTHON APPLICATION PROGRAMMING'
];

List<String> Ece7Courses = [
  'COMPUTER NETWORKS ',
  'VLSI DESIGN ',
  'REAL TIME SYSTEM',
  'SATELLITE COMMUNICATION ',
  'DIGITAL IMAGEPROCESSING',
  'DSP ALGORITHMS and ARCHITECTURE',
  'IoT & WIRELESS SENSOR NETWORKS',
  'AUTOMOTIVE ELECTRONICS',
  'MULTIMEDIA COMMUNICATION',
  'CRYPTOGRAPHY',
  'MACHINE LEARNING WITH PYTHON',
  'COMPUTER NETWORKS LAB',
  'VLSI LAB ',
  'COMMUNICATION THEORY',
  'NEURAL NETWORKS ',
];
List<String> Ece8Courses = [
  'WIRELESS AND CELLULAR COMMUNICATION ',
  'NETWORK SECURITY ',
  'MICRO ELECTROMECHANICAL SYSTEMS',
  'RADAR ENGINEERING',
  'OPTICAL COMMUNICATION NETWORKS',
  'BIOMEDICAL SIGNAL PROCESSING',
];

List<String> Civil3Courses = [
  'Mathematics-3',
  'Strength of Materials',
  'Fluid Mechanics',
  'BUILDING MATERIALS AND CONSTRUCTION',
  'BASIC SURVEYING ',
  'ENGINEERING GEOLOGY',
  'COMPUTER AIDED BUILDING PLANNING AND DRAWING',
  'BUILDING MATERIALS TESTING LABORATORY',
];
