name: entangle
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  rflutter_alert: ^1.0.3
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.7+3
  google_sign_in:
  http: ^0.12.1
  firebase_auth: ^0.18.0+1
  firebase_dynamic_links: ^0.6.0
  firebase_core:
  share: ^0.6.4+3
  youtube_player_flutter: ^6.1.1
  url_launcher: ^5.4.11
  dio:
  path_provider: ^1.6.11
  dartpedia: ^1.6.6
  connectivity: ^0.4.9+2
  flappy_search_bar: ^1.7.2
  provider:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - courseImages/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Roboto-bold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: Roboto-medium
      fonts:
        - asset: fonts/Roboto-Medium.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
