name: entangle
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  rflutter_alert: ^1.0.3
  flutter:
    sdk: flutter
  splashscreen:

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.7+3
  google_sign_in: ^4.5.1
  http: ^0.12.1
  firebase_auth: ^0.16.1
  firebase_dynamic_links: ^0.5.1
  share: ^0.6.4+3
  youtube_player_flutter: ^6.1.1
  url_launcher: ^5.4.11
  dio: ^3.0.9
  path_provider: ^1.6.11


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - courseImages/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches-Regular.ttf
    - family: Bebas Neue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf

