name: entangle
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  rflutter_alert: ^1.0.3
  flutter:
    sdk: flutter
  splashscreen:

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - p-cycle/
    - c-cycle/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches-Regular.ttf
    - family: Bebas Neue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf

